services:
  omop-db:
    image: docker.io/postgres:14.1
    restart: on-failure
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_DB: ohdsi
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD:-strong_ohdsi_password}

  webapi:
    environment:
      DATASOURCE_USERNAME: postgres
      DATASOURCE_DRIVERCLASSNAME: org.postgresql.Driver
      DATASOURCE_URL: jdbc:postgresql://omop-db:5432/ohdsi
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      FLYWAY_DATASOURCE_USERNAME: postgres
      FLYWAY_DATASOURCE_DRIVERCLASSNAME: org.postgresql.Driver
      FLYWAY_DATASOURCE_URL: jdbc:postgresql://omop-db:5432/ohdsi
      FLYWAY_LOCATIONS: classpath:db/migration/postgresql
